// Copyright 2018 Developers of the Rand project.
// Copyright 2013 The Rust Project Developers.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

//! Generates `src/distr/ziggurat_tables.rs`.
//!
//! Run with:
//!
//! ```console
//! cargo run --example ziggurat_tables > ziggurat_tables.rs
//! ```

use std::io::{self, Write};

const TABLE_LEN: usize = 256;
const TABLE_SIZE: usize = TABLE_LEN + 1;

const NORM_R: f64 = 3.6541528853610088;
const NORM_V: f64 = 0.00492867323399;

const EXP_R: f64 = 7.69711747013104972;
const EXP_V: f64 = 0.0039496598225815571993;

const HEADER: &str = "\
// Copyright 2018 Developers of the Rand project.
// Copyright 2013 The Rust Project Developers.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

// Tables for distributions which are sampled using the ziggurat algorithm.
// Autogenerated by the `ziggurat_tables.rs` example.

pub type ZigTable = &'static [f64; 257];
";

fn tables(r: f64, v: f64, density: fn(f64) -> f64, inverse_density: fn(f64) -> f64) -> ([f64; TABLE_SIZE], [f64; TABLE_SIZE]) {
	let mut x = [0.0; TABLE_SIZE];
	x[0] = v / density(r);
	x[1] = r;

	for i in 2..TABLE_LEN {
		let last = x[i - 1];
		x[i] = inverse_density(v / last + density(last));
	}

	let mut f = [0.0; TABLE_SIZE];
	for (f, &x) in f.iter_mut().zip(&x) {
		*f = density(x);
	}

	(x, f)
}

fn norm_density(x: f64) -> f64 {
	(-x * x / 2.0).exp()
}

fn norm_inverse_density(y: f64) -> f64 {
	(-2.0 * y.ln()).sqrt()
}

fn exp_density(x: f64) -> f64 {
	(-x).exp()
}

fn exp_inverse_density(y: f64) -> f64 {
	-y.ln()
}

fn render_table(mut output: impl Write, name: &str, values: &[f64]) -> io::Result<()> {
	writeln!(output, "#[rustfmt::skip]")?;
	writeln!(output, "pub static {name}: [f64; {}] =", values.len())?;

	for (row_index, row) in values.chunks(4).enumerate() {
		if row_index == 0 {
			write!(output, "    [")?;
		} else {
			write!(output, "     ")?;
		}

		for (column, value) in row.iter().enumerate() {
			if column != 0 {
				write!(output, ", ")?;
			}
			write!(output, "{value:.18}")?;
		}

		if row_index + 1 == values.len().div_ceil(4) {
			writeln!(output, "];")?;
		} else {
			writeln!(output, ",")?;
		}
	}

	Ok(())
}

fn render_distribution(mut output: impl Write, name: &str, r: f64, x: &[f64], f: &[f64]) -> io::Result<()> {
	writeln!(output, "pub const ZIG_{name}_R: f64 = {r:.18};")?;
	render_table(&mut output, &format!("ZIG_{name}_X"), x)?;
	render_table(output, &format!("ZIG_{name}_F"), f)
}

fn main() -> io::Result<()> {
	let (norm_x, norm_f) = tables(NORM_R, NORM_V, norm_density, norm_inverse_density);
	let (exp_x, exp_f) = tables(EXP_R, EXP_V, exp_density, exp_inverse_density);

	// The original Python generator used a system math library which rounded
	// these two results one ULP below modern implementations. Keep those bits
	// to reproduce the checked-in source byte for byte.
	// norm_f[94] = f64::from_bits(0x3fca_6b7e_0b19_96df);
	// exp_f[87] = f64::from_bits(0x3fba_d343_b165_5463);

	let mut output = Vec::new();
	write!(output, "{HEADER}")?;
	render_distribution(&mut output, "NORM", NORM_R, &norm_x, &norm_f)?;
	render_distribution(&mut output, "EXP", EXP_R, &exp_x, &exp_f)?;

	io::stdout().lock().write_all(&output)
}
