use super::*;


// These are the supported ChaCha round counts and the only variants certified through SecureRng

/// [`ChaChaRng`] with 8 rounds.
pub type ChaCha8Rng = ChaChaRng<8>;
impl SecureRng for ChaChaRng<8> {}

/// [`ChaChaRng`] with 12 rounds.
pub type ChaCha12Rng = ChaChaRng<12>;
impl SecureRng for ChaChaRng<12> {}

/// [`ChaChaRng`] with 20 rounds.
pub type ChaCha20Rng = ChaChaRng<20>;
impl SecureRng for ChaChaRng<20> {}


/// Daniel J. Bernstein's ChaCha adapted as a deterministic random number generator.
///
/// # Serialization security
///
/// With the `serde` feature, the serialized generator state contains the secret seed and buffered keystream.
/// Anyone who obtains it can reproduce the generator's stream. Protect serialized state with the same care as the original seed.
#[derive(Clone)]
#[repr(transparent)]
pub struct ChaChaRng<const N: usize> {
	inner: BlockRngImpl<ChaChaState<N>>,
}

impl<const N: usize> ChaChaRng<N> where Self: SecureRng {
	/// Creates a new instance seeded from system entropy.
	///
	/// This method is the recommended way to construct PRNGs since it is convenient and securely seeded.
	///
	/// # Panics
	///
	/// If [`getentropy`] is unable to provide secure entropy this method will panic.
	///
	/// # Examples
	///
	/// ```
	/// let mut rand = urandom::rng::ChaCha12Rng::new();
	/// let value: i32 = rand.random();
	/// ```
	#[inline]
	#[cfg(feature = "getrandom")]
	pub fn new() -> Random<ChaChaRng<N>> {
		Self::from_seed(util::getrandom())
	}

	/// Creates a new instance seeded from another generator.
	///
	/// This may be useful when needing to rapidly seed many instances from a master CSPRNG, and to allow forking of PRNGs.
	#[inline]
	pub fn from_rng<R: ?Sized + SecureRng>(rand: &mut Random<R>) -> Random<ChaChaRng<N>> {
		Self::from_seed(rand.random_bytes())
	}

	/// Creates a new instance directly from its native 256-bit seed.
	///
	/// Callers supplying entropy for cryptographic use must ensure the seed is secret and generated by a cryptographically secure entropy source.
	///
	/// # Examples
	///
	/// ```
	/// let seed = [1, 2, 3, 4, 5, 6, 7, 8];
	/// let mut rand = urandom::rng::ChaCha12Rng::from_seed(seed);
	/// let value: u64 = rand.random();
	/// ```
	#[inline]
	pub fn from_seed(seed: [u32; 8]) -> Random<ChaChaRng<N>> {
		Random::from(from_seed(seed))
	}

	/// Creates a reproducible instance by expanding a 64-bit seed into the native 256-bit seed.
	///
	/// This **is not suitable for cryptography**, as should be clear given that the input size is only 64 bits.
	///
	/// The seed expansion and resulting stream are covered by the [reproducibility guarantee](crate::rng#reproducibility-guarantee).
	///
	/// # Examples
	///
	/// ```
	/// let mut rand = urandom::rng::ChaCha12Rng::from_seed_u64(42);
	/// let value: i32 = rand.random();
	/// assert_eq!(value, 631540493);
	/// ```
	#[inline]
	pub fn from_seed_u64(seed: u64) -> Random<ChaChaRng<N>> {
		let low = (seed & 0xffffffff) as u32;
		let high = (seed >> 32) as u32;
		Self::from_seed([low, high, low, high, low, high, low, high])
	}
}

impl<const N: usize> Sealed for ChaChaRng<N> {}

impl<const N: usize> core::fmt::Debug for ChaChaRng<N> {
	fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
		// The state contains the seed and buffered keystream.
		f.debug_struct("ChaChaRng").finish_non_exhaustive()
	}
}

impl<const N: usize> Rng for ChaChaRng<N> where Self: SecureRng {
	#[inline]
	fn next_u32(&mut self) -> u32 {
		self.inner.next_u32()
	}
	#[inline]
	fn next_u64(&mut self) -> u64 {
		self.inner.next_u64()
	}
	#[inline]
	fn fill_bytes(&mut self, buf: &mut [MaybeUninit<u8>]) {
		self.inner.fill_bytes(buf);
	}
}

impl<const N: usize> JumpRng for ChaChaRng<N> where Self: SecureRng {
	/// Selects the next stream.
	#[inline]
	fn jump(&mut self) {
		self.inner.jump();
	}

	/// Derives two independently keyed descendants from the next 512 output bits.
	#[inline]
	fn fork(mut self) -> (Self, Self) {
		let left_seed = core::array::from_fn(|_| self.next_u32());
		let right_seed = core::array::from_fn(|_| self.next_u32());
		(from_seed(left_seed), from_seed(right_seed))
	}
}

#[inline]
fn from_seed<const N: usize>(seed: [u32; 8]) -> ChaChaRng<N> where ChaChaRng<N>: SecureRng {
	let state = ChaChaState::new(seed, 1, 0);
	let inner = BlockRngImpl::new(state);
	ChaChaRng { inner }
}


//----------------------------------------------------------------
// ChaCha implementation details
// https://cr.yp.to/chacha/chacha-20080128.pdf
// http://loup-vaillant.fr/tutorials/chacha20-design

use core::fmt;

#[allow(dead_code)]
mod slp;

#[cfg(all(any(target_arch = "x86", target_arch = "x86_64"), target_feature = "avx2"))]
mod avx2;

#[allow(dead_code)]
#[cfg(all(any(target_arch = "x86", target_arch = "x86_64"), target_feature = "sse2"))]
mod sse2;

cfg_if::cfg_if! {
	if #[cfg(all(any(target_arch = "x86", target_arch = "x86_64"), target_feature = "avx2"))] {
		use self::avx2::block as chacha_block;
	}
	else if #[cfg(all(any(target_arch = "x86", target_arch = "x86_64"), target_feature = "sse2"))] {
		use self::sse2::block as chacha_block;
	}
	else {
		use self::slp::block as chacha_block;
	}
}

const CN: usize = 4; // Concurrent ChaCha instances
const CONSTANT: [u32; 4] = [0x61707865, 0x3320646e, 0x79622d32, 0x6b206574];

#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(transparent)]
pub struct ChaChaOutput([[u32; 16]; CN]);

unsafe impl dataview::Pod for ChaChaOutput {}

#[derive(Clone)]
#[repr(C)]
pub struct ChaChaState<const N: usize> {
	seed: [u32; 8],
	counter: [u32; 2],
	stream: [u32; 2],
}

unsafe impl<const N: usize> dataview::Pod for ChaChaState<N> {}

impl<const N: usize> ChaChaState<N> {
	#[inline]
	pub fn new(seed: [u32; 8], counter: u64, stream: u64) -> ChaChaState<N> {
		ChaChaState {
			seed,
			counter: [counter as u32, (counter >> 32) as u32],
			stream: [stream as u32, (stream >> 32) as u32],
		}
	}
	#[inline]
	pub fn get_state(&self) -> [[u32; 4]; 4] {
		[
			CONSTANT,
			[self.seed[0], self.seed[1], self.seed[2], self.seed[3]],
			[self.seed[4], self.seed[5], self.seed[6], self.seed[7]],
			[self.counter[0], self.counter[1], self.stream[0], self.stream[1]],
		]
	}
	#[inline]
	pub fn get_counter(&self) -> u64 {
		(self.counter[1] as u64) << 32 | self.counter[0] as u64
	}
	#[inline]
	pub fn set_counter(&mut self, counter: u64) {
		self.counter[0] = counter as u32;
		self.counter[1] = (counter >> 32) as u32;
	}
	#[inline]
	#[allow(dead_code)] // Used by the non-AVX2 backends.
	pub fn add_counter(&self, counter: u64) -> ChaChaState<N> {
		let mut this = self.clone();
		this.set_counter(self.get_counter().wrapping_add(counter));
		this
	}
	#[inline]
	pub fn get_stream(&self) -> u64 {
		(self.stream[1] as u64) << 32 | self.stream[0] as u64
	}
	#[inline]
	pub fn set_stream(&mut self, stream: u64) {
		self.stream[0] = stream as u32;
		self.stream[1] = (stream >> 32) as u32;
	}
}

impl<const N: usize> BlockRng for ChaChaState<N> {
	type Output = ChaChaOutput;

	#[inline(never)]
	fn generate(&mut self, random: &mut Self::Output) {
		chacha_block(self, &mut random.0);
		#[cfg(target_endian = "big")]
		for block in &mut random.0 {
			for word in block {
				*word = word.to_le();
			}
		}
	}

	#[inline]
	fn jump(&mut self) {
		self.set_stream(self.get_stream().wrapping_add(1));
	}
}

impl<const N: usize> fmt::Debug for ChaChaState<N> {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		f.debug_struct("ChaChaState")
			.field("seed", &format_args!("{:x?}", self.seed))
			.field("counter", &self.get_counter())
			.field("stream", &self.get_stream())
			.finish()
	}
}

#[cfg(feature = "serde")]
mod s;

#[cfg(feature = "getrandom")]
#[cfg(test)]
mod tests;

#[test]
fn test_from_seed() {
	use super::tests::ReproVector;
	ReproVector {
		u32_value: 0x8e8c_7b1b,
		u64_value: 0xb2e5_d228_2adf_5af2,
		f32_bits: 0x3fbe_15cb,
		f64_bits: 0x3ff9_8221_61ef_ea99,
		bytes: [0xd2, 0xa4, 0x82, 0x60, 0x7b, 0xa5, 0xfa, 0xab, 0x56, 0x1f, 0x94, 0xb1, 0x41, 0x88, 0xd4, 0xed, 0x2c],
		after_jump: 0x89fb_79ac_b50b_7644,
		fork_left: 0x3145_a75e_8ba1_c6eb,
		fork_right: 0xd5e4_0d30_82a9_fb9b,
	}.check(ChaCha8Rng::from_seed_u64(42));

	ReproVector {
		u32_value: 0x25a4_8b0d,
		u64_value: 0x3689_639d_33fe_74a6,
		f32_bits: 0x3fc0_a61e,
		f64_bits: 0x3ffc_13f7_890d_7ea8,
		bytes: [0x9b, 0x67, 0xdc, 0xbc, 0x72, 0x39, 0x96, 0xfc, 0xc3, 0x81, 0x7b, 0xac, 0xfa, 0x5e, 0x14, 0xcb, 0xd1],
		after_jump: 0x77f6_df64_9f89_0ed9,
		fork_left: 0xe4ba_5342_4574_e251,
		fork_right: 0x6a76_99f0_8c63_ebb3,
	}.check(ChaCha12Rng::from_seed_u64(42));

	ReproVector {
		u32_value: 0x673a_7168,
		u64_value: 0x8da2_dba7_badf_9172,
		f32_bits: 0x3fc1_ee4e,
		f64_bits: 0x3ff1_ddb6_993e_14a1,
		bytes: [0x1f, 0x4f, 0xce, 0xfd, 0xfc, 0x17, 0x26, 0x31, 0x42, 0x1d, 0x2e, 0xea, 0x61, 0x00, 0xab, 0x72, 0x79],
		after_jump: 0x81f7_1ca1_87b3_485b,
		fork_left: 0x4b96_469b_3e90_7350,
		fork_right: 0xc564_52c4_15b8_8d1e,
	}.check(ChaCha20Rng::from_seed_u64(42));

	ReproVector {
		u32_value: 0xa09a_fa6c,
		u64_value: 0x5215_5cdb_e072_3b83,
		f32_bits: 0x3fa3_41e8,
		f64_bits: 0x3ff4_8641_b2ee_b0c8,
		bytes: [0x04, 0x9d, 0x30, 0x32, 0x7e, 0xee, 0x85, 0x16, 0x22, 0xc6, 0x5e, 0xa3, 0x58, 0xaa, 0xb7, 0xd5, 0x0d],
		after_jump: 0x6fac_49bc_247c_6632,
		fork_left: 0x9225_f952_3fba_9468,
		fork_right: 0xa819_0d24_8fe2_641b,
	}.check(ChaCha12Rng::from_seed([
		0x0302_0100, 0x0706_0504, 0x0b0a_0908, 0x0f0e_0d0c,
		0x1312_1110, 0x1716_1514, 0x1b1a_1918, 0x1f1e_1d1c,
	]));
}
