use super::*;

/// Fast RNG, with 64 bits of state, that can be used to initialize the state of other generators.
#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[repr(transparent)]
pub struct SplitMix64Rng {
	state: u64,
}

impl SplitMix64Rng {
	/// Creates a new instance seeded from system entropy.
	///
	/// This method is the recommended way to construct PRNGs since it is convenient and securely seeded.
	///
	/// # Panics
	///
	/// If [`getentropy`] is unable to provide secure entropy this method will panic.
	///
	/// # Examples
	///
	/// ```
	/// let mut rand = urandom::rng::SplitMix64Rng::new();
	/// let value: i32 = rand.random();
	/// ```
	#[inline]
	pub fn new() -> Random<SplitMix64Rng> {
		Self::from_seed(util::getrandom())
	}

	/// Creates a new instance seeded from another generator.
	///
	/// This may be useful when needing to rapidly seed many instances from a master PRNG, and to allow forking of PRNGs.
	///
	/// The master PRNG should use a sufficiently different algorithm from the child PRNG (ideally a CSPRNG) to avoid correlations between the child PRNGs.
	#[inline]
	pub fn from_rng<R: Rng + ?Sized>(rand: &mut Random<R>) -> Random<SplitMix64Rng> {
		Self::from_seed(rand.next_u64())
	}

	/// Creates a new instance directly from its native 64-bit seed.
	///
	/// Callers supplying entropy should ensure the seed is generated by a suitable entropy source.
	///
	/// # Examples
	///
	/// ```
	/// let seed = 0x0123_4567_89ab_cdef;
	/// let mut rand = urandom::rng::SplitMix64Rng::from_seed(seed);
	/// let value: u64 = rand.random();
	/// ```
	#[inline]
	pub fn from_seed(seed: u64) -> Random<SplitMix64Rng> {
		Random::from(SplitMix64Rng { state: seed })
	}

	/// Creates a reproducible instance from a 64-bit seed.
	///
	/// The resulting stream is covered by the [reproducibility guarantee](crate::rng#reproducibility-guarantee).
	///
	/// # Examples
	///
	/// ```
	/// let mut rand = urandom::rng::SplitMix64Rng::from_seed_u64(42);
	/// let value: u32 = rand.random();
	/// assert_eq!(value, 3184996902);
	/// ```
	#[inline]
	pub fn from_seed_u64(seed: u64) -> Random<SplitMix64Rng> {
		Self::from_seed(seed)
	}
}

impl Sealed for SplitMix64Rng {}

impl Rng for SplitMix64Rng {
	#[inline]
	fn next_u32(&mut self) -> u32 {
		(next(&mut self.state) >> 32) as u32
	}
	#[inline]
	fn next_u64(&mut self) -> u64 {
		next(&mut self.state)
	}
	#[inline(never)]
	fn fill_bytes(&mut self, buf: &mut [MaybeUninit<u8>]) {
		let mut rng = self.clone();
		util::rng_fill_bytes(&mut rng, buf);
		*self = rng;
	}
}

impl JumpRng for SplitMix64Rng {
	/// Advances the generator by 2<sup>40</sup> state transitions.
	#[inline]
	fn jump(&mut self) {
		jump(&mut self.state)
	}

	/// Derives two new starting points from this generator.
	///
	/// SplitMix64 has only 64 bits of state and a fixed increment, so its descendants are not guaranteed to occupy disjoint streams.
	#[inline]
	fn fork(mut self) -> (Self, Self) {
		let left = SplitMix64Rng { state: next(&mut self.state) };
		let right = SplitMix64Rng { state: next(&mut self.state) };
		(left, right)
	}
}

#[cfg(feature = "serde")]
#[test]
fn serde() {
	tests::check_serde_initial_state(SplitMix64Rng::new());
	tests::check_serde_middle_state(SplitMix64Rng::new());
}

//----------------------------------------------------------------
// SplitMix64Rng implementation details

pub(super) const GOLDEN_GAMMA: u64 = 0x9e3779b97f4a7c15;

#[inline]
fn next(x: &mut u64) -> u64 {
	*x = x.wrapping_add(GOLDEN_GAMMA);
	mix64(*x)
}
#[inline]
fn jump(x: &mut u64) {
	*x = x.wrapping_add(GOLDEN_GAMMA << 40);
}

// https://zimbry.blogspot.com/2011/09/better-bit-mixing-improving-on.html
#[inline]
pub(super) fn mix64(mut z: u64) -> u64 {
	z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
	z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
	return z ^ (z >> 31);
}
